# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Hexo CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.2.0
      with:
        # Private SSH key to register in the SSH agent
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: actions/checkout@v2
    - uses: snickerbockers/submodules-init@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g hexo-cli
    - run: npm i
    - run: hexo clean && hexo g --debug && gulp
    - name: Commit files
      run: |
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "CI" -a
        git pull
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.CI_TOKEN }}
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.1.2
      env:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # Remote host
        REMOTE_HOST: hw.kherrisan.cn
        # Remote user
        REMOTE_USER: root
        # Source directory
        SOURCE: docs
        # Target directory
        TARGET: /vaw/www/html
